name: hi

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - name: fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: cargo test --all -- --nocapture
